# Generated by Django 5.2 on 2025-04-04 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cycle_used', models.FloatField()),
                ('route_estimated_distance', models.FloatField(max_length=55)),
                ('route_estimated_duration', models.FloatField(max_length=55)),
                ('current_location_name', models.CharField(max_length=255)),
                ('pickup_location_name', models.CharField(max_length=255)),
                ('dropoff_location_name', models.CharField(max_length=255)),
                ('truck_number', models.CharField(max_length=50)),
                ('carried_product_name', models.CharField(max_length=20)),
                ('total_daily_miles', models.FloatField()),
                ('duty_status', models.TextField()),
                ('driving_hours_0_11', models.FloatField(default=0)),
                ('driving_hours_12_17', models.FloatField(default=0)),
                ('driving_hours_18_23', models.FloatField(default=0)),
                ('off_duty_hours_0_11', models.FloatField(default=0)),
                ('off_duty_hours_12_17', models.FloatField(default=0)),
                ('off_duty_hours_18_23', models.FloatField(default=0)),
                ('on_duty_hours_0_11', models.FloatField(default=0)),
                ('on_duty_hours_12_17', models.FloatField(default=0)),
                ('on_duty_hours_18_23', models.FloatField(default=0)),
                ('sleeper_berth_hours_0_11', models.FloatField(default=0)),
                ('sleeper_berth_hours_12_17', models.FloatField(default=0)),
                ('sleeper_berth_hours_18_23', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
